const wordList = [
  { word: "apple", hint: "A red fruit." },
  { word: "chair", hint: "For sitting." },
  { word: "cloud", hint: "In the sky." },
  { word: "plane", hint: "Flies high." },
  { word: "mouse", hint: "Small animal." },
  { word: "grape", hint: "Purple fruit." },
  { word: "brick", hint: "Builds walls." },
  { word: "zebra", hint: "Striped animal." },
  { word: "eagle", hint: "A large bird." },
  { word: "flute", hint: "A wind instrument." },
  { word: "horse", hint: "A farm animal." },
  { word: "earth", hint: "Our planet." },
  { word: "bread", hint: "Made of flour." },
  { word: "water", hint: "Essential liquid." },
  { word: "knife", hint: "For cutting." },
  { word: "sheep", hint: "Woolly animal." },
  { word: "beach", hint: "Sandy place." },
  { word: "torch", hint: "Gives light." },
  { word: "ocean", hint: "Large water body." },
  { word: "table", hint: "Has four legs." },
  { word: "clock", hint: "Tells time." },
  { word: "brick", hint: "Used in construction." },
  { word: "plant", hint: "Needs water." },
  { word: "train", hint: "Runs on tracks." },
  { word: "queen", hint: "Female ruler." },
  { word: "shell", hint: "Found on beaches." },
  { word: "stone", hint: "Small rock." },
  { word: "smile", hint: "Facial expression." },
  { word: "drink", hint: "Quenches thirst." },
  { word: "globe", hint: "Earth model." },
  { word: "books", hint: "Contain stories." },
  { word: "storm", hint: "Bad weather." },
  { word: "brush", hint: "For painting." },
  { word: "shirt", hint: "Upper clothing." },
  { word: "frost", hint: "Ice on surfaces." },
  { word: "juice", hint: "Fruit drink." },
  { word: "light", hint: "Removes darkness." },
  { word: "candy", hint: "Sugary treat." },
  { word: "train", hint: "Transport mode." },
  { word: "robot", hint: "Automated machine." },
  { word: "green", hint: "Grass color." },
  { word: "child", hint: "A young person." },
  { word: "paper", hint: "For writing." },
  { word: "music", hint: "Pleasant sound." },
  { word: "teeth", hint: "Used for chewing." },
  { word: "heart", hint: "Pumps blood." },
  { word: "crown", hint: "For a king." },
  { word: "piano", hint: "Has keys." },
  { word: "space", hint: "Beyond Earth." }
];
